on:
  push:
  pull_request:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - name: nodenv/setup-nodenv
      uses: nodenv/actions-setup-nodenv@v2.0.4
    - uses: actions/checkout@v1
    - name: install tslint
      run: npm install tslint
    - name: lint
      run: npm run test:lint
      
